# Jekyll Configuration for Design System Documentation

# Site settings
title: Design System Documentation
description: Centralized design system guidance and component documentation
baseurl: "/design-system-docs-website"
url: "https://aarushivenk.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (these are included in github-pages gem)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  components:
    output: true
    permalink: /:collection/:name/
  patterns:
    output: true
    permalink: /:collection/:name/
  layouts:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "components"
    values:
      layout: "page"
      category: "components"
  - scope:
      path: ""
      type: "patterns"
    values:
      layout: "page"
      category: "patterns"
  - scope:
      path: ""
      type: "layouts"
    values:
      layout: "page"
      category: "layouts"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
