# Jekyll Configuration for Design System Documentation

# Site settings
title: Design System Documentation
description: Centralized design system guidance and component documentation
baseurl: "/design-system-docs-website"
url: "https://aarushivenk.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (these are included in github-pages gem)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  about:
    output: true
    permalink: /:collection/:name/
  branding:
    output: true
    permalink: /:collection/:name/
  content-style-guide:
    output: true
    permalink: /:collection/:name/
  accessibility:
    output: true
    permalink: /:collection/:name/
  layouts:
    output: true
    permalink: /:collection/:name/
  patterns:
    output: true
    permalink: /:collection/:name/
  components:
    output: true
    permalink: /:collection/:name/
  foundations:
    output: true
    permalink: /:collection/:name/
  guidelines:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "page"
      category: "about"
  - scope:
      path: ""
      type: "branding"
    values:
      layout: "page"
      category: "branding"
  - scope:
      path: ""
      type: "content-style-guide"
    values:
      layout: "page"
      category: "content-style-guide"
  - scope:
      path: ""
      type: "accessibility"
    values:
      layout: "page"
      category: "accessibility"
  - scope:
      path: ""
      type: "layouts"
    values:
      layout: "layout"
      category: "layouts"
  - scope:
      path: ""
      type: "patterns"
    values:
      layout: "pattern"
      category: "patterns"
  - scope:
      path: ""
      type: "components"
    values:
      layout: "component"
      category: "components"
  - scope:
      path: ""
      type: "foundations"
    values:
      layout: "foundation"
      category: "foundations"
  - scope:
      path: ""
      type: "guidelines"
    values:
      layout: "guideline"
      category: "guidelines"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
