# Jekyll Configuration for Design System Documentation

# Site settings
title: Design System Documentation
description: Centralized design system guidance and component documentation
baseurl: "/design-system-docs-website" # the subpath of your site, e.g. /blog
url: "https://aarushivenk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections for organizing content
collections:
  about:
    output: true
    permalink: /:collection/:name/
  branding:
    output: true
    permalink: /:collection/:name/
  content-style-guide:
    output: true
    permalink: /:collection/:name/
  accessibility:
    output: true
    permalink: /:collection/:name/
  layouts:
    output: true
    permalink: /:collection/:name/
  patterns:
    output: true
    permalink: /:collection/:name/
  components:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "about"
    values:
      layout: "page"
      category: "about"
  - scope:
      path: ""
      type: "branding"
    values:
      layout: "page"
      category: "branding"
  - scope:
      path: ""
      type: "content-style-guide"
    values:
      layout: "page"
      category: "content-style-guide"
  - scope:
      path: ""
      type: "accessibility"
    values:
      layout: "page"
      category: "accessibility"
  - scope:
      path: ""
      type: "layouts"
    values:
      layout: "page"
      category: "layouts"
  - scope:
      path: ""
      type: "patterns"
    values:
      layout: "page"
      category: "patterns"
  - scope:
      path: ""
      type: "components"
    values:
      layout: "page"
      category: "components"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - foundations-old/
  - guidelines-old/
